CREATE TABLE categories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE restaurants(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE restaurant_category(
    id_restaurant INT NOT NULL,
    id_category INT NOT NULL,

    PRIMARY KEY (id_restaurant, id_category),

    CONSTRAINT fk_rest_cat_restaurant FOREIGN KEY (id_restaurant)
        REFERENCES restaurants(id) ON DELETE CASCADE,

    CONSTRAINT fk_rest_cat_category FOREIGN KEY (id_category)
        REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE operating_hours(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(20) NOT NULL,
    close_hour TIME(0) NOT NULL,
    open_hour TIME(0) NOT NULL,
    id_restaurant INT NOT NULL,

    CONSTRAINT fk_operating_hour_restaurant FOREIGN KEY (id_restaurant)
        REFERENCES restaurants(id) ON DELETE CASCADE
);

CREATE TABLE products(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id_restaurant INT NOT NULL,

    CONSTRAINT fk_product_restaurant FOREIGN KEY (id_restaurant)
        REFERENCES restaurants(id) ON DELETE CASCADE
);
